CREATE DATABASE tipsit CHARACTER SET utf8 COLLATE utf8_general_ci;
USE tipsit;

CREATE TABLE user (
  id INT(3) NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE posts (
  id INT(3) NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  content VARCHAR(300) NOT NULL,
  date VARCHAR(255) NOT NULL,
  claps INT(3) DEFAULT 0,
  keyword VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE bulbs (
  id INT(3) NOT NULL AUTO_INCREMENT,
  id_user INT(3) NOT NULL,
  id_post INT(3) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE favoris (
  id INT(3) NOT NULL AUTO_INCREMENT,
  id_user_favoris INT(3) NOT NULL,
  username VARCHAR(20) NOT NULL,
  content VARCHAR(300) NOT NULL,
  date VARCHAR(255) NOT NULL,
  claps INT(3) DEFAULT 0,
  keyword VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;