CREATE DATABASE tipsit CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE tipsit;

CREATE TABLE utilisateur (
  id INT(3) NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  mdp VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE posts (
  id INT(3) NOT NULL AUTO_INCREMENT,
   VARCHAR(20) NOT NULL,
  content VARCHAR(300) NOT NULL,
  date VARCHAR(255) NOT NULL,
  claps INT(3) NOT NULL,
  keyword VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;