CREATE DATABASE Tipsit CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE Tipsit;

CREATE TABLE user (
  id INT(3) NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE posts (
  id INT(3) NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  content VARCHAR(300) NOT NULL,
  date VARCHAR(255) NOT NULL,
  claps INT(3) NOT NULL,
  keyword VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB;